services:
  soldat2:
    build: .
    container_name: soldat2
    network_mode: host
    volumes:
      - ./server:/opt/soldat2/
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_GREET_MESSAGE=${SERVER_GREET_MESSAGE}